version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /mnt/registry/data
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: basic-realm
    path: /mnt/registry/passwd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
