FROM manorrock/tomcat:9
UN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates librados2 apache2-utils && \
    rm -rf /var/lib/apt/lists/*
COPY target/admin.war /usr/local/tomcat/webapps/ROOT.war
