FROM manorrock/tomcat:arm32v6-9
RUN ["cross-build-start"]
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates librados2 apache2-utils && \
    rm -rf /var/lib/apt/lists/*
COPY target/admin.war /usr/local/tomcat/webapps/ROOT.war
RUN ["cross-build-end"]
