name: build
on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '*'  
jobs:
  admin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: mvn -B --ntp package
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker images
      run: |
        cd admin
        mvn -B --ntp -P docker clean install docker:push
        cd ../registry
        mvn -B --ntp -P docker clean install docker:push
