name: build
on: 
  push:
    branches:
      - 'master'
jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build amd64 image
      run: |
        cd registry
        docker build -f Dockerfile.amd64 -t manorrock/toyger:amd64-latest .
        docker push manorrock/toyger:amd64-latest
    - name: Build arm32v6 image
      run: |
        cd registry
        docker build -f Dockerfile.arm32v6 -t manorrock/toyger:arm32v6-latest .
        docker push manorrock/toyger:arm32v6-latest
    - name: Push Docker manifest
      run: |
        cd registry
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/toyger:latest \
          manorrock/toyger:amd64-latest \
          manorrock/toyger:arm32v6-latest
        docker manifest annotate manorrock/toyger:latest \
          manorrock/toyger:amd64-latest --os linux --arch amd64
        docker manifest annotate manorrock/toyger:latest \
          manorrock/toyger:arm32v6-latest --os linux --arch arm
        docker manifest push manorrock/toyger:latest
  admin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build amd64 image
      run: |
        cd admin
        docker build -f Dockerfile.amd64 -t manorrock/toyger-admin:amd64-latest .
        docker push manorrock/toyger-admin:amd64-latest
    - name: Build arm32v6 image
      run: |
        cd admin
        docker build -f Dockerfile.arm32v6 -t manorrock/toyger-admin:arm32v6-latest .
        docker push manorrock/toyger-admin:arm32v6-latest
    - name: Push Docker manifest
      run: |
        cd admin
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/toyger-admin:latest \
          manorrock/toyger-admin:amd64-latest \
          manorrock/toyger-admin:arm32v6-latest
        docker manifest annotate manorrock/toyger-admin:latest \
          manorrock/toyger-admin:amd64-latest --os linux --arch amd64
        docker manifest annotate manorrock/toyger-admin:latest \
          manorrock/toyger-admin:arm32v6-latest --os linux --arch arm
        docker manifest push manorrock/toyger-admin:latest
