name: release
on:
  push:
    tags:        
      - 'v*'
jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build amd64 image
      run: |
        cd registry
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}+1}
        docker build -f Dockerfile.amd64 -t manorrock/toyger:amd64-$VERSION .
        docker push manorrock/toyger:amd64-$VERSION
    - name: Push Docker manifest
      run: |
        cd registry
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}+1}
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/toyger:$VERSION \
          manorrock/toyger:amd64-$VERSION
        docker manifest annotate manorrock/toyger:$VERSION \
          manorrock/toyger:amd64-$VERSION --os linux --arch amd64
        docker manifest push manorrock/toyger:$VERSION
  admin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B -DskipTests=true -f pom.xml install
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build Docker images
      run: |
        cd admin
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}+1}
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker build -f Dockerfile.amd64 -t manorrock/toyger-admin:amd64--$VERSION .
        docker buildx build --platform linux/arm/v6 -t manorrock/toyger-admin:arm32v6--$VERSION -f Dockerfile.arm32v6 .
        docker manifest create manorrock/toyger-admin:$VERSION \
          manorrock/toyger-admin:amd64-$VERSION && \
          manorrock/toyger-admin:arm32v6-$VERSION
        docker manifest annotate manorrock/toyger-admin:$VERSION \
          manorrock/toyger-admin:amd64-$VERSION --os linux --arch amd64
        docker manifest annotate manorrock/toyger-admin:$VERSION \
          manorrock/toyger-admin:arm32v6-$VERSION --os linux --arch arm
        docker manifest push manorrock/toyger-admin:$VERSION
